# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: caf55a263f5bf389149a292188056fa1ed54fc93c196b88cbbc4a4aeec6378d6bf11534fde727ddef0af9a5250c834b6937c37d1771ed7e4c0cf96601e03d826

test:
  secret_key_base: fe939a8a5810124f993ea27c05d352826cfcb0c1591b14f2dd7f94d33393b56b7c8262dbedac15b59a14d40d5b932423fd4ab81428fb57ad14771592282b6c62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
